# -*- coding: utf-8 -*-
"""Python_Assessment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11MZny-R4tT8t_UgAwDtZYVXXb29hF-PO
"""



"""Write a Python program that simulates an online marketplace where users can view, add,
purchase, search, and edit items for sale. The program should have the following features:
● The program should start by displaying a menu with the following options:
○ 1. View items
○ 2. Add items
○ 3. Purchase items
○ 4. Search items
○ 5. Edit items
○ 6. Exit.
"""

items_for_sale=[]
def display_menu():
  print("Menu:")
  print("1.view_Item")
  print("2.Add_Items")
  print("3.Purchase_Items")
  print("4.Search_Items")
  print("5.Edit_Items")
  print("6.Exit")
def view_items():
  if not items_for_sale:
    print("no items available for sale:")
  else:
    print("items for sale:")
    print("{} {} {}".format("Name", "Price", "Quantity"))
    for item in items_for_sale:
      print("{} {} {}".format(item['Name'], item['Price'], item['Quantity']))
def add_item():
  name=input("enter the name of the item:")
  price=float(input("enter the quantity of item"))
  quantity=int(input("enter the quantity"))
  new_item={'name':name, 'price':price, 'quantity':quantity}
  ites_for_sale.append(new_item)
def purchase_item():
  i_name = input("Enter the item name")
  found = False
  for i in items_for_sale:
    if item['name'] == i_name:
      found = True
      q = int(input("enter the quantity to purchase"))
      if q <= item['quantity']:
        total_cost = item["price"]*q
        item["quantity"] -= q
      else:
        print(f"sorry only{item["quantity"]}{item["name"] available}")

def search_item():
  key = input("enter a keyword to search for items")
  match_items = [item for item in items_for_sale if key.lower() in item["name"].lower()]
  if not match_items:
    print("no items found for matching{"key"}."format(key))
  else:
    print("{}{}{}".format(item["Name"], item["price"], item["quantity"]))
    for i in match_items:
      print("{}{}{}".format(item['name'], item['price'], item['quantity']))

def edit_item():
  i_name = input("enter the name of the item you need to edit")
  f = False
  for i in items_for_sale:
    if item["name"] == i_name:
      f = True
      n_name = input("Enter a new name")
      n_price = input("Enter the new price")
      n_quantity = input("Enter the new quantity")
      if n_name:
        item['name'] = n_name
      if n_price:
        item['price'] = n_price
      if n_quantity:
        item['quantity'] = n_quantity

    if not f:
      print("{} item was not found".format(i_name))

  while True:
    display_menu()
    choice = input("enter your choice 1-6:")

    if choice == '1':
      view_items()
    elif choice == '2':
      add_items()
    elif choice == '3':
      purchase_items()
    elif choice == '4':
      search_items()
    elif choice == '5':
      edit_item()
    elif choice == '6':
      print("Exiting the mrketplace. thank you")
      break
    else:
      print("invalid choice, please select a valid choice")